### ISSUE TITLE
Add dependabot service to repository

### ISSUE THREAD

**Issue by aldrichtr** [aldrichtr/stitch#100]
Start with github actions:
```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
```
